### ISSUE TITLE
Doesnt work for me

### ISSUE THREAD

**Issue by beatrizdemiguelperez** [alexspeller/kondiment#1]
I wanna try this tool but get this:
kondiment.rb:26:in `build!': undefined method `write' for #<Pathname:0x007fa6b9244b88> (NoMethodError)

**Comment by alexspeller** [comment]
Huh that's weird, what ruby version are you on?

**Comment by beatrizdemiguelperez** [comment]
> ruby -v
> ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

**Comment by alexspeller** [comment]
Ah, I think it must need ruby 2.1 or greater to work
